apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  type: {{ .Values.service.type }}
  selector:
    app: postgres-db
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
